### ISSUE TITLE
value ThrowablePartial is not a member of object org.danielnixon.extrawarts.ExtraWart

### ISSUE THREAD

**Issue by marconilanna** [danielnixon/extrawarts#4]
Could you please publish 1.0.1 again? I'm using `addSbtPlugin("org.danielnixon" % "sbt-extrawarts" % "1.0.1")` and I get: `value ThrowablePartial is not a member of object org.danielnixon.extrawarts.ExtraWart`

**Comment by danielnixon** [comment]
Mea culpa. 1.0.2 will fix it as soon as I can get Sonatype to cooperate... In the meantime you can use `Wart.custom("org.danielnixon.extrawarts.ThrowablePartial")` as a workaround.
